Added BioQuickscan options to model project
Amsterdam/masterlist pull request #55
Opened 2022-02-09 15:08 UTC by mabdala

Added BIO Quickscan to project-model

2022-02-09 15:09 UTC, jklardie requested changes

2022-02-09 16:01 UTC, mabdala commented on src/project/models.py
> +    bio_quickscan_path = models.CharField(max_length=255, blank=True, null=True)
Migrations gemaakt, tests succevol

2022-02-10 10:33 UTC, jklardie requested changes
Testcases missen nog

2022-02-16 14:05 UTC, jklardie approved these changes
Het toevoegen van alle tests was wat mij betreft niet nodig (enkel voor de velden die je zelf hebt toegevoegd), maar is wel mooi meegenomen.

2022-02-16 14:05 UTC, merged